# frontend-green-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  labels:
    app: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend-green
          image: iammanjyyot/blue-green-deployment_frontend-green:latest
          ports:
            - containerPort: 3200
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:5000"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-green-service
spec:
  selector:
    app: frontend-green
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
